### ISSUE TITLE
Question regarding input genomes!

### ISSUE THREAD

**Issue by maesaar** [JackAidley/PhasomeIt#5]
I have ~5000 C. jejuni genomes from 11 STs. For now I am using to run PhasomeIt 11x using different STs per run. I want to compare STs using PhasomeIt. What do you think is it ok to use PhasomeIt that way or should I ran PhasomeIt one time including all 5000 isolates from different STs?

Thank you

**Comment by JackAidley** [comment]
I think it is unlikely that PhasomeIt will cope with so many different genomes. The most I used it with was a bit over 200, and most of the work was done with about 70 or so. The display of the data produced was therefore not designed with such numbers in mind, and the processing complexity and memory demands increase with the square of the number of genomes analysed.

I would suggest perhaps selecting some "representative" genomes from each ST and then comparing them.

**Comment by maesaar** [comment]
So you mean select subset approx. 200 isolates from different STs and then run PhasomeIt all combined in same run?

**Comment by maesaar** [comment]
Update: I have finished two different ST runs:
1) n=325;
2) n=493.
Now I will run three other runs with other STs with approx 1100 isolates in each.

Additional question: Are the runs comparable when running different STs in each runs?

**Comment by maesaar** [comment]
@JackAidley update: I have finished two different ST runs:
1) n=325;
2) n=493.

Now I will run three other runs with other STs with approx 1100 isolates in each.

Additional question: Are the runs comparable when running different STs in each runs?

**Comment by JackAidley** [comment]
Hi Maesaar,

I am not sure what you mean by comparable. The numbering, naming and potentially grouping of PV tracts may be different depending on what genomes are included. Which PV tracts are identified, the length of those tracts, and the predicted On/Off state will be the same.

You can mitigate this, to an extent, by including one or more common reference strains (e.g. 11168) and then using the '--firstStrain' and '--firstSpecies' parameters to control the placement of the reference strain(s) so that it is in the first place and thus any PV genes it identifies as homologous to these will get consistently numbered/named. PV genes that aren't part of this may still be inconsistent.

**Comment by maesaar** [comment]
Thank you @JackAidley

**Comment by maesaar** [comment]
Forgot to elaborate what I meant by comparable. My initial idea was to compare number of PV genes in different STs groups and different sources. So my question was is it correct to use different PhasomeIt runs (one ST per run) for such of comparision or should all the isolates (from different STs) be included in one run?

Thank you for the answer @JackAidley

**Comment by JackAidley** [comment]
In terms of just numbers that will be fine. Most of the work Phasome_It_ does is about grouping the different tracts, but numbers will be the same between batches.

**Comment by maesaar** [comment]
Good to know! Thank you again!
