### ISSUE TITLE
Some NCBI reference genomes not recognized

### ISSUE THREAD

**Issue by CuypersBart** [JackAidley/PhasomeIt#7]
Hi, 

I am trying to use gbf files obtained from NCBI to use Phasomelt.
However, the crawler only finds SOME of the gbf files and converts them to fasta, before running the other steps. Other .gbf files are ignored without any indication of an error. 

Do you have any idea why it does not recognise some gbf files?
Example of a gbf file that does not work (note, the extension is '.gbf' on my laptop, but converted now to '.txt' for uploading to github:
[GCF_001432345.1.txt](https://github.com/JackAidley/PhasomeIt/files/8482097/GCF_001432345.1.txt)
Example of a gbf file that does work: 
[GCF_000759575.2.txt](https://github.com/JackAidley/PhasomeIt/files/8482107/GCF_000759575.2.txt)

Secondary question: is multithreading possible, e.g. for the BLAST step?

**Comment by JackAidley** [comment]
Hi CuypersBart,

The files which are not working are being excluded because it is detecting them as being plasmid sequences when, in fact, the files contain both plasmid and non-plasmid sequences. The logic in genomecrawler.py, lines 109/10 is incorrect for this kind of mixed file. I will make a correction and upload it after the Easter break. In the meantime, removing the plasmid sequence will work.

The BLAST step should automatically be multi-threaded, but the analysis step is written in single threaded Python.

All the best,

Jack.

**Comment by JackAidley** [comment]
I have pushed a fix for this bug, and created a new release 1.1.5 with the fix included.

Let me know if you have any further problems, otherwise I'll close this bug in a few days

**Comment by CuypersBart** [comment]
Thank you for your fast reply last week (temporary fix worked perfectly) and now!

It works perfectly now with NCBI gbff files, also on genomes with a lot of scaffolds.
